# NAME OF AGENTS
AGENT_ANALYZER: "ANALYZER"
AGENT_CHATTER: "CHATTER"
AGENT_GRADER: "GRADER"
AGENT_GENERATOR: "GENERATOR"
AGENT_FAQ: "FAQ"
AGENT_ROUTER: "ROUTER"
AGENT_RETRIEVER: "RETRIEVER"
AGENT_REPORTER: "REPORTER"
AGENT_SUPERVISOR: "SUPERVISOR"
AGENT_CAKE_CONSULTING: "CAKE_CONSULTING"
AGENT_ORDER_INFO: "ORDER_INFO"
AGENT_ORDER_DETAILS: "ORDER_DETAILS"
AGENT_HELLO: "HELLO"

AGENT_OTHER: "OTHER"
AGENT_NOT_ENOUGH_INFO: "NOT_ENOUGH_INFO"
AGENT_HUMAN: "HUMAN"
AGENT_COMPLAINT: "COMPLAINT"
AGENT_BILL: "BILL"