# EMBEDDING
MODEL_EMBEDDING: "models/sup-SimCSE-VietNamese-phobert-base"
DIM_EMBEDDING: 1536
CHUNK_SIZE: 2400
CHUNK_OVERLAP: 500

# EMBEDING IMAGE
MODEL_EMBEDDING_IMAGE: "models/mobilenet_v3_small_075_224_embedder.tflite"
IMAGE_DIM_EMBEDDING: 1024

# CAKE DETECT MODEL
MODEL_CAKE_DETECT: "models/yolo11s.pt"