ENV: "PROD"
DEBUG: False
VERSION: "1.0"
SERVER_NAME: "0.0.0.0"
PORT_NUMBER: 5000

DOMAIN_SERVER: "https://98d6-42-113-16-217.ngrok-free.app/minio/"
#AUTHEN
SECRET_AUTH_KEY:
ALGORITHM: "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES: 30

# DOMAIN
DOMAIN_MINIO: "http://milvus-minio:9000"


# MILVUS DATABASE
URI_CONNECTION_MILVUS: "http://milvus-standalone:19530"
DB_NAME: "chatbot_cake_consulting"
TOKEN_CONNECTION_MILVUS:
MILVUS_DATABASE_NAME: "chatbot_cake_consulting"

# PATH STATIC, TEMPLATE
STATIC_DIR: "web/static"
TEMPLATE_DIR: "web/templates"

# MYSQL DATABASE
URI_CONNECTION_MYSQL: "mysql"
PORT_MYSQL: 3306
DB_NAME_MYSQL: "DOCUMENTS_CAKE_MANAGER"
USER_NAME_MYSQL: "root"
PASSWORD_MYSQL: "root"

# MINIO FILEBASE
URI_CONNECTION_MINIO: "http://milvus-minio:9000"
BUCKET_NAME_MINIO: "chatbot"
ACCESS_KEY_MINIO: "minioadmin"
SECRET_KEY_MINIO: "minioadmin"

# FAQ
FAQ_THRESHOLD: 0.85

# ON OFF Zalo FB
META_ROUTER: False

# Messenger/facebook config
GRAPH_FACEBOOK_DOMAIN: "https://graph.facebook.com"

PAGE_FACEBOOK_ACCESS_TOKEN:
PERSONA_ID_CHATBOT_FACEBOOK:
APP_SECRET_FACEBOOK:
APP_ID_FACEBOOK:


# Default recommend question:
RECOMMEND_QUESTIONS: [ ]
RECOMMEND_SOURCES: [ "web", "default_recommend" ]
RECOMMEND_NUMB: 3

# ChatGPT

OPENAI_API_KEY:
LLM_MODEL: "gpt-4.1-2025-04-14"
# HISTORY CHAT
HISTORY_MESSAGES_NUMB: 5

# LLM
#GEMINI_MODEL_NAME: "gemini-1.5-flash"
GEMINI_MODEL_NAME: "gemini-1.5-flash-8b"
GOOGLE_API_KEY:

# PLATFORMS
PLATFORMS: [ "facebook" ]


ORS_API_KEY: