CAKE_CONSULTING_PROMPT_TEMPLATE: ./app/configs/prompts/CAKE_CONSULTING_PROMPT_TEMPLATE.md
ORDER_INFO_PROMPT_TEMPLATE: ./app/configs/prompts/ORDER_INFO_PROMPT_TEMPLATE.md
BILL_PROMPT_TEMPLATE: ./app/configs/prompts/BILL_PROMPT_TEMPLATE.md
